#!/bin/sh

if [ $# -eq 0 ]
then
    port=1512
else
    port=$1
fi

log_file='SMART.log'
: > $log_file

while :; do
    content=`nc -l $port`
    log="$port @ `date +%s` @@ $content"
    echo $log >> $log_file
    echo $log
    ./analyser
done
