#!/usr/bin/ruby

require 'rubygems'
require 'sinatra'

get '/' do
    'Hello World!</p>
    <a href="readme">README</a></p>
    <a href="log">SMART.log</a></p>
    '
end

get '/readme' do
    File.readlines("README")
end

get '/log' do
    log='<meta http-equiv="refresh" content="10">'
    f = File.open("SMART.log")
    f.each { |line|
        log+=line
        log+='</p>'
    }
    f.close
    log

end

